### ISSUE TITLE
Ubuntu packages

### ISSUE THREAD

**Issue by gonrada** [ASCIIDuck/asciiduck-sssd#3]
The packages installed for Debian machines includes sudo, https://github.com/ASCIIDuck/asciiduck-sssd/blob/master/manifests/params.pp#L37. This cause the following error when sudo is already defined by another module: Duplicate declaration: Package[sudo] is already declared in file.

Should sudo be removed from the packages installed? Or could the module check to see if they are already defined?

**Comment by ASCIIDuck** [comment]
A little background, Ubuntu has two packages sudo and sudo-ldap. The former works with sssd while the later does not. Including the sudo package ensures that sudo is installed and sudo-ldap is removed. Including it is just barely on the edge of being appropriate for this module, though I'm willing to admit that I included it for convenience in my local environment more than being certain that it's appropriate for this module.

The more I think about it the more appropriate it seems to remove sudo from the package list of this module and instead have that be managed outside this package. In the meantime the work around is to override the packages parameter in hiera for Debian machines.

**Comment by ASCIIDuck** [comment]
With the release today this should no longer be an issue.
